import { useState, useEffect } from 'react';
import { useAuth } from '../context/AuthContext';
import Layout from '../components/Layout';
import axios from 'axios';
import { FileText, Download, Calendar, CheckCircle, XCircle, Filter } from 'lucide-react';
import jsPDF from 'jspdf';

export default function ReportsPage() {
  const { token } = useAuth();
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [filter, setFilter] = useState('all'); // 'all', 'healthy', 'diseased'

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      const response = await axios.get('/api/reports', {
        headers: { Authorization: `Bearer ${token}` }
      });
      setReports(response.data.reports);
    } catch (error) {
      console.error('Failed to fetch reports:', error);
    } finally {
      setLoading(false);
    }
  };

  const filteredReports = reports.filter(report => {
    if (filter === 'all') return true;
    if (filter === 'healthy') return report.status === 'Healthy';
    if (filter === 'diseased') return report.status === 'Diseased';
    return true;
  });

  const downloadReportPDF = (report) => {
    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('Cattle Disease Detection Report', 105, 25, { align: 'center' });
    
    // Report Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    let y = 60;
    
    doc.text(`Report ID: ${report.report_id}`, 20, y);
    y += 10;
    doc.text(`Date: ${new Date(report.timestamp).toLocaleString()}`, 20, y);
    y += 15;
    
    // Status
    doc.setFontSize(16);
    doc.text('Status:', 20, y);
    doc.setTextColor(report.status === 'Healthy' ? 34 : 220, report.status === 'Healthy' ? 197 : 38, report.status === 'Healthy' ? 94 : 38);
    doc.text(report.status, 50, y);
    doc.setTextColor(0, 0, 0);
    y += 15;
    
    if (report.status === 'Diseased') {
      doc.setFontSize(12);
      doc.text(`Disease: ${report.disease_name}`, 20, y);
      y += 10;
      doc.text(`Stage: ${report.stage}`, 20, y);
      y += 10;
    }
    
    doc.text(`Confidence: ${report.confidence}%`, 20, y);
    y += 15;
    
    // Precautions
    if (report.precautions && report.precautions.length > 0) {
      doc.setFontSize(14);
      doc.text('Precautions:', 20, y);
      y += 10;
      doc.setFontSize(11);
      report.precautions.forEach((precaution, index) => {
        const lines = doc.splitTextToSize(`${index + 1}. ${precaution}`, 170);
        lines.forEach(line => {
          doc.text(line, 25, y);
          y += 7;
        });
      });
    }
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Cattle Disease Detection System', 105, 280, { align: 'center' });
    
    doc.save(`cattle-report-${report.report_id}.pdf`);
  };

  if (loading) {
    return (
      <Layout>
        <div className="flex items-center justify-center h-64">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600"></div>
        </div>
      </Layout>
    );
  }

  return (
    <Layout>
      <div className="max-w-7xl mx-auto">
        {/* Header */}
        <div className="flex justify-between items-center mb-8">
          <div>
            <h1 className="text-3xl font-bold text-gray-800">My Reports</h1>
            <p className="text-gray-600 mt-1">View and manage your cattle health reports</p>
          </div>
          
          {/* Filter Dropdown */}
          <div className="flex items-center gap-3">
            <span className="text-sm text-gray-600 flex items-center gap-2">
              <Filter className="w-4 h-4" />
              Filter by:
            </span>
            <select
              value={filter}
              onChange={(e) => setFilter(e.target.value)}
              className="px-4 py-2 bg-white border border-gray-300 rounded-xl font-medium text-gray-700 focus:outline-none focus:ring-2 focus:ring-primary-500"
            >
              <option value="all">All Reports</option>
              <option value="healthy">Healthy Only</option>
              <option value="diseased">Diseased Only</option>
            </select>
          </div>
        </div>

        {/* Stats Cards */}
        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8">
          <div className="bg-gradient-to-br from-blue-500 to-blue-600 rounded-2xl p-6 text-white shadow-lg">
            <p className="text-blue-100 text-sm mb-1">Total Reports</p>
            <p className="text-4xl font-bold">{reports.length}</p>
          </div>
          <div className="bg-gradient-to-br from-success-500 to-success-600 rounded-2xl p-6 text-white shadow-lg">
            <p className="text-green-100 text-sm mb-1">Healthy</p>
            <p className="text-4xl font-bold">{reports.filter(r => r.status === 'Healthy').length}</p>
          </div>
          <div className="bg-gradient-to-br from-danger-500 to-danger-600 rounded-2xl p-6 text-white shadow-lg">
            <p className="text-red-100 text-sm mb-1">Diseased</p>
            <p className="text-4xl font-bold">{reports.filter(r => r.status === 'Diseased').length}</p>
          </div>
        </div>

        {/* Reports Table */}
        {filteredReports.length === 0 ? (
          <div className="bg-white rounded-2xl shadow-lg p-12 text-center border border-gray-100">
            <div className="w-20 h-20 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <FileText className="w-10 h-10 text-gray-400" />
            </div>
            <p className="text-gray-600 text-lg font-medium">No reports found</p>
            <p className="text-gray-500 mt-2">Upload an image to generate your first report</p>
          </div>
        ) : (
          <div className="bg-white rounded-2xl shadow-lg overflow-hidden border border-gray-100">
            {/* Table Header */}
            <div className="bg-primary-700 text-white px-6 py-4">
              <h2 className="text-lg font-semibold">Client Reports</h2>
            </div>

            {/* Table */}
            <div className="overflow-x-auto">
              <table className="w-full">
                <thead className="bg-gray-50 border-b border-gray-200">
                  <tr>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">Report ID</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">Date</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">Disease</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">Status</th>
                    <th className="px-6 py-4 text-left text-sm font-semibold text-gray-700">Confidence</th>
                    <th className="px-6 py-4 text-center text-sm font-semibold text-gray-700">Actions</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-gray-200">
                  {filteredReports.map((report) => (
                    <tr key={report.report_id} className="hover:bg-gray-50 transition-colors">
                      <td className="px-6 py-4">
                        <span className="font-mono text-sm text-gray-800">{report.report_id}</span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2 text-sm text-gray-600">
                          <Calendar className="w-4 h-4" />
                          {new Date(report.timestamp).toLocaleDateString('en-US', {
                            month: '2-digit',
                            day: '2-digit',
                            year: 'numeric'
                          })}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <span className="text-sm text-gray-800">
                          {report.status === 'Diseased' ? report.disease_name : '-'}
                        </span>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          {report.status === 'Healthy' ? (
                            <>
                              <CheckCircle className="w-5 h-5 text-success-500" />
                              <span className="px-3 py-1 bg-success-100 text-success-700 rounded-full text-sm font-medium">
                                Healthy
                              </span>
                            </>
                          ) : (
                            <>
                              <XCircle className="w-5 h-5 text-danger-500" />
                              <span className="px-3 py-1 bg-danger-100 text-danger-700 rounded-full text-sm font-medium">
                                Diseased
                              </span>
                            </>
                          )}
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center gap-2">
                          <div className="flex-1 bg-gray-200 rounded-full h-2 max-w-[100px]">
                            <div
                              className={`h-2 rounded-full ${
                                report.confidence >= 80 ? 'bg-success-500' : 
                                report.confidence >= 50 ? 'bg-warning-500' : 'bg-danger-500'
                              }`}
                              style={{ width: `${report.confidence}%` }}
                            ></div>
                          </div>
                          <span className="text-sm font-semibold text-gray-700">{report.confidence}%</span>
                        </div>
                      </td>
                      <td className="px-6 py-4">
                        <div className="flex items-center justify-center gap-2">
                          <button
                            onClick={() => downloadReportPDF(report)}
                            className="px-4 py-2 bg-primary-600 hover:bg-primary-700 text-white rounded-lg text-sm font-medium transition-colors flex items-center gap-2"
                          >
                            <Download className="w-4 h-4" />
                            Download
                          </button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </div>
        )}
      </div>
    </Layout>
  );
}
