import { useState } from 'react';
import { useAuth } from '../context/AuthContext';
import Layout from '../components/Layout';
import axios from 'axios';
import { Upload, CheckCircle, XCircle, Download, Volume2 } from 'lucide-react';
import jsPDF from 'jspdf';

export default function UploadPage() {
  const { token } = useAuth();
  const [selectedImage, setSelectedImage] = useState(null);
  const [preview, setPreview] = useState(null);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState(null);
  const [error, setError] = useState('');

  const handleImageSelect = (e) => {
    const file = e.target.files[0];
    if (file) {
      setSelectedImage(file);
      setPreview(URL.createObjectURL(file));
      setResult(null);
      setError('');
    }
  };

  const handleUpload = async () => {
    if (!selectedImage) {
      setError('Please select an image first');
      return;
    }

    try {
      setLoading(true);
      setError('');

      const formData = new FormData();
      formData.append('image', selectedImage);

      const response = await axios.post('/api/predict', formData, {
        headers: {
          'Authorization': `Bearer ${token}`,
          'Content-Type': 'multipart/form-data'
        }
      });

      setResult(response.data.report);
    } catch (err) {
      setError(err.response?.data?.message || 'Prediction failed. Please try again.');
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  const handleReset = () => {
    setSelectedImage(null);
    setPreview(null);
    setResult(null);
    setError('');
  };

  const speakResult = () => {
    if (!result) return;
    
    const text = `
      Status: ${result.status}.
      ${result.status === 'Diseased' ? `Disease: ${result.disease_name}. Stage: ${result.stage}.` : ''}
      Confidence: ${result.confidence} percent.
      Precautions: ${result.precautions.join('. ')}
    `;
    
    const utterance = new SpeechSynthesisUtterance(text);
    speechSynthesis.speak(utterance);
  };

  const downloadPDF = () => {
    if (!result) return;

    const doc = new jsPDF();
    
    // Header
    doc.setFillColor(37, 99, 235);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(24);
    doc.text('Cattle Disease Detection Report', 105, 25, { align: 'center' });
    
    // Report Details
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(12);
    let y = 60;
    
    doc.text(`Report ID: ${result.report_id}`, 20, y);
    y += 10;
    doc.text(`Date: ${new Date(result.timestamp).toLocaleString()}`, 20, y);
    y += 15;
    
    // Status
    doc.setFontSize(16);
    doc.text('Status:', 20, y);
    doc.setTextColor(result.status === 'Healthy' ? 34 : 220, result.status === 'Healthy' ? 197 : 38, result.status === 'Healthy' ? 94 : 38);
    doc.text(result.status, 50, y);
    doc.setTextColor(0, 0, 0);
    y += 15;
    
    if (result.status === 'Diseased') {
      doc.setFontSize(12);
      doc.text(`Disease: ${result.disease_name}`, 20, y);
      y += 10;
      doc.text(`Stage: ${result.stage}`, 20, y);
      y += 10;
    }
    
    doc.text(`Confidence: ${result.confidence}%`, 20, y);
    y += 15;
    
    // Precautions
    doc.setFontSize(14);
    doc.text('Precautions:', 20, y);
    y += 10;
    doc.setFontSize(11);
    result.precautions.forEach((precaution, index) => {
      const lines = doc.splitTextToSize(`${index + 1}. ${precaution}`, 170);
      lines.forEach(line => {
        doc.text(line, 25, y);
        y += 7;
      });
    });
    
    // Recommendations
    if (result.recommendations && result.recommendations.length > 0) {
      y += 5;
      doc.setFontSize(14);
      doc.text('Recommendations:', 20, y);
      y += 10;
      doc.setFontSize(11);
      result.recommendations.forEach((rec, index) => {
        const lines = doc.splitTextToSize(`${index + 1}. ${rec}`, 170);
        lines.forEach(line => {
          doc.text(line, 25, y);
          y += 7;
        });
      });
    }
    
    // Footer
    doc.setFontSize(10);
    doc.setTextColor(128, 128, 128);
    doc.text('Generated by Cattle Disease Detection System', 105, 280, { align: 'center' });
    
    doc.save(`cattle-report-${result.report_id}.pdf`);
  };

  return (
    <Layout>
      <div className="max-w-6xl mx-auto">
        <h1 className="text-3xl font-bold text-gray-800 mb-8">Upload Image - Disease Detection</h1>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
          {/* Upload Section */}
          <div className="card">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Upload Image</h2>
            
            <div className="border-2 border-dashed border-gray-300 rounded-lg p-8 text-center mb-4">
              {preview ? (
                <div className="relative">
                  <img src={preview} alt="Preview" className="max-h-64 mx-auto rounded-lg" />
                  <button
                    onClick={handleReset}
                    className="absolute top-2 right-2 bg-red-500 text-white p-2 rounded-full hover:bg-red-600"
                  >
                    <XCircle className="w-5 h-5" />
                  </button>
                </div>
              ) : (
                <div>
                  <Upload className="w-16 h-16 text-gray-400 mx-auto mb-4" />
                  <p className="text-gray-600 mb-2">Click to upload or drag and drop</p>
                  <p className="text-sm text-gray-500">PNG, JPG up to 10MB</p>
                </div>
              )}
              <input
                type="file"
                accept="image/*"
                onChange={handleImageSelect}
                className="hidden"
                id="image-upload"
              />
            </div>

            <label htmlFor="image-upload" className="btn-secondary w-full block text-center cursor-pointer mb-4">
              Select Image
            </label>

            <button
              onClick={handleUpload}
              disabled={!selectedImage || loading}
              className="btn-primary w-full disabled:opacity-50 disabled:cursor-not-allowed"
            >
              {loading ? (
                <span className="flex items-center justify-center gap-2">
                  <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-white"></div>
                  Analyzing...
                </span>
              ) : (
                'Analyze Image'
              )}
            </button>

            {error && (
              <div className="mt-4 bg-red-50 border border-red-200 text-red-700 px-4 py-3 rounded-lg">
                {error}
              </div>
            )}
          </div>

          {/* Results Section */}
          <div className="card">
            <h2 className="text-xl font-semibold text-gray-800 mb-4">Prediction Results</h2>
            
            {result ? (
              <div className="space-y-4">
                {/* Status Badge */}
                <div className={`p-4 rounded-lg ${result.status === 'Healthy' ? 'bg-green-50 border border-green-200' : 'bg-red-50 border border-red-200'}`}>
                  <div className="flex items-center gap-3">
                    {result.status === 'Healthy' ? (
                      <CheckCircle className="w-8 h-8 text-green-600" />
                    ) : (
                      <XCircle className="w-8 h-8 text-red-600" />
                    )}
                    <div>
                      <p className="text-sm font-medium text-gray-600">Status</p>
                      <p className={`text-2xl font-bold ${result.status === 'Healthy' ? 'text-green-700' : 'text-red-700'}`}>
                        {result.status}
                      </p>
                    </div>
                  </div>
                </div>

                {/* Disease Info */}
                {result.status === 'Diseased' && (
                  <div className="space-y-2">
                    <div className="flex justify-between items-center p-3 bg-gray-50 rounded-lg">
                      <span className="font-medium text-gray-700">Disease:</span>
                      <span className="text-gray-900">{result.disease_name}</span>
                    </div>
                    <div className="flex justify-between items-center p-3 bg-gray-50 rounded-lg">
                      <span className="font-medium text-gray-700">Stage:</span>
                      <span className="text-gray-900">{result.stage}</span>
                    </div>
                  </div>
                )}

                {/* Confidence */}
                <div className="p-4 bg-blue-50 border border-blue-200 rounded-lg">
                  <p className="text-sm font-medium text-blue-600 mb-2">Confidence Score</p>
                  <div className="flex items-center gap-3">
                    <div className="flex-1 bg-blue-200 rounded-full h-3">
                      <div
                        className="bg-blue-600 h-3 rounded-full transition-all"
                        style={{ width: `${result.confidence}%` }}
                      ></div>
                    </div>
                    <span className="text-xl font-bold text-blue-700">{result.confidence}%</span>
                  </div>
                </div>

                {/* Precautions */}
                <div className="p-4 bg-yellow-50 border border-yellow-200 rounded-lg">
                  <p className="font-semibold text-gray-800 mb-3">Precautions:</p>
                  <ul className="space-y-2">
                    {result.precautions.map((precaution, index) => (
                      <li key={index} className="flex gap-2 text-sm text-gray-700">
                        <span className="text-yellow-600">•</span>
                        <span>{precaution}</span>
                      </li>
                    ))}
                  </ul>
                </div>

                {/* Action Buttons */}
                <div className="flex gap-3">
                  <button
                    onClick={downloadPDF}
                    className="flex-1 btn-success flex items-center justify-center gap-2"
                  >
                    <Download className="w-5 h-5" />
                    Download PDF
                  </button>
                  <button
                    onClick={speakResult}
                    className="btn-secondary flex items-center justify-center gap-2"
                  >
                    <Volume2 className="w-5 h-5" />
                    Listen
                  </button>
                </div>
              </div>
            ) : (
              <div className="text-center py-12 text-gray-500">
                <Upload className="w-16 h-16 mx-auto mb-4 opacity-50" />
                <p>Upload an image to see prediction results</p>
              </div>
            )}
          </div>
        </div>
      </div>
    </Layout>
  );
}
